[build]
  publish = "public"
  functions = "netlify/functions"

# pretty URL: /api?service=weather  ->  the function
[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
